###
# SPDX-License-Identifier: MPL-2.0
#
# Author: Bernd rederlechner <bernd.rederlechner@t-systems.com
#
# Build generated artefacts after assembly 
# for a server release
#

name: MCLOUD custom server release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Release increment'
        required: true
        type: number

jobs:
  assemble-custom:
    uses: nextmcloud/.github/.github/workflows/nmc-custom-assembly.yml@master
    with:
      trunk: 'master'
      stable: ${{ vars.CUSTOM_BRANCH || 'nmcstable/25.0.6' }}
      result: ${{ format('customisation-{0}', vars.CUSTOM_BRANCH || 'nmcstable/25.0.6' ) }}
    secrets: inherit
  build-custom:
    uses: nextmcloud/.github/.github/workflows/nmc-custom-server-build.yml@master
    needs: assemble-custom
    with:
      stable: ${{ vars.CUSTOM_BRANCH || 'nmcstable/25.0.6' }}
      assembly: ${{ format('customisation-{0}', vars.CUSTOM_BRANCH || 'nmcstable/25.0.6' ) }}
      tag: ${{ format('{0}-{1}', vars.CUSTOM_BRANCH || 'nmcstable/25.0.6' , inputs.increment) }}
      prerelease: false
    secrets: inherit
