###
# SPDX-License-Identifier: AGPL-3.0
#
# Author: Bernd rederlechner <bernd.rederlechner@t-systems.com>
#
# Builds a stable release package based on a release assembly
# customisation-<version>-<increment>
#
# As soon as a package is deployed to production, the tag and the branch
# MUST STAY FOR 2 years and not deleted.
#
# Release packages, tags and customisation branches not delivered to production should
# be deleted asap a newer release is available.
#


name: MCLOUD custom server release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Release increment'
        required: true
        type: number

jobs:
  assemble-custom:
    uses: nextmcloud/.github/.github/workflows/nmc-custom-assembly.yml@nmc/2027-build-test-rtoth
    with:
      trunk: 'master'
      stable: ${{ vars.CUSTOM_BRANCH_26_26 || 'stable26' }}
      result: ${{ format('customisation-{0}-{1}', vars.CUSTOM_BRANCH_26 || 'nmcstable/26.0.9', inputs.increment ) }}
    secrets: inherit
  build-custom:
    uses: nextmcloud/.github/.github/workflows/nmc-custom-server-build.yml@nmc/2027-build-test-rtoth
    needs: assemble-custom
    with:
      stable: ${{ vars.CUSTOM_BRANCH_26 || 'stable26' }}
      assembly: ${{ format('customisation-{0}-{1}', vars.CUSTOM_BRANCH_26 || 'stable26', inputs.increment ) }}
      tag: ${{ format('{0}-{1}', vars.CUSTOM_BRANCH_26 || 'stable26' , inputs.increment) }}
      prerelease: false
    secrets: inherit


