###
# SPDX-License-Identifier: MPL-2.0
#
# Author: Bernd rederlechner <bernd.rederlechner@t-systems.com
#
# Assemble a customisation for recent trunk
# (only master changes, no backports)
#
# The assembly ssafeguards that all customisations for master
# are available and merge properly.
#

name: MCLOUD custom versions

on:
  workflow_dispatch:

jobs:
  build-custom:
    strategy:
      fail-fast: false
      matrix:
        custombase: [ "master", "nmcstable/25.0.6" ]
    uses: nextmcloud/.github/workflows/nmc-custom-assembly.yml@master
    with:
      trunk: "master"
      stable: ${{ matrix.custombase }}
      result: ${{ format('customisation-{0}-{1}', github.actor, matrix.custombase) }}
    secrets: inherit
